# Generated by Django 3.0.8 on 2022-01-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_auto_20220125_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception3',
            name='active',
        ),
        migrations.AddField(
            model_name='reception0',
            name='active',
            field=models.BooleanField(default=True, verbose_name='面会番号が有効か無効か'),
        ),
    ]
