# Generated by Django 3.0.8 on 2022-01-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_auto_20220125_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reception3',
            old_name='reception_id',
            new_name='r_id',
        ),
    ]
