# Generated by Django 3.0.8 on 2022-01-25 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visit', '0006_auto_20220125_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception3',
            name='r_id',
        ),
        migrations.AddField(
            model_name='reception3',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='email'),
            preserve_default=False,
        ),
    ]
